const initialState = {
  version: '0.2.0',
  items: {
    0: {
      content: 'Initialize your project from EAD',
      subItemIds: [1, 9],
      order: 'vertical',
      subdirection: 'row',
      isDropDisabled: true,
      isDragDisabled: true,
      expand: true,
    },
    1: {
      content: 'Elements',
      subItemIds: [2, 3, 4, 5, 6, 7, 8],
      order: 'vertical',
      subdirection: 'column',
      isDropDisabled: true,
      isDragDisabled: true,
      expand: true,
      factory: true,
      category: 'factory',
    },
    2: {
      content: '/|\\',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: true,
      factory: true,
      association: true,
      expand: true,
      category: 'association',
    },
    3: {
      content: '|',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: true,
      factory: true,
      association: true,
      expand: true,
      category: 'association',
    },
    4: {
      content: ':',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: true,
      factory: true,
      association: true,
      expand: true,
      category: 'association',
    },
    5: {
      content: 'attribute container',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: true,
      factory: true,
      type: 'string',
      expand: true,
      attributeContainer: true,
      category: 'attributeContainer',
    },
    6: {
      content: 'attribute',
      subItemIds: [],
      attribute: true,
      order: 'vertical',
      subdirection: 'column',
      isDropDisabled: true,
      factory: true,
      type: 'string',
      expand: true,
      category: 'attribute',
    },
    7: {
      content: 'entity',
      subItemIds: [],
      order: 'vertical',
      subdirection: 'column',
      factory: true,
      entity: true,
      expand: true,
      isDropDisabled: true,
      category: 'entity',
      cloneable: true,
      cloneChildren: [],
    },
    8: {
      content: 'entity container',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      factory: true,
      entityContainer: true,
      expand: true,
      isDropDisabled: true,
      category: 'entityContainer',
    },
    9: {
      content: 'EAD',
      subItemIds: [10, 11],
      order: 'horizontal',
      subdirection: 'row',
      isDragDisabled: true,
      expand: true,
      category: 'EAD',
    },
    10: {
      content: 'entity container',
      subItemIds: [],
      order: 'vertical',
      subdirection: 'column',
      entityContainer: true,
      expand: true,
      category: 'entityContainer',
      factory: false,
      isDropDisabled: false,
    },
    11: {
      content: 'entity container',
      subItemIds: [],
      order: 'vertical',
      subdirection: 'column',
      entityContainer: true,
      expand: true,
      category: 'entityContainer',
      factory: false,
      isDropDisabled: false,
    },
  },
  restrictedDropId: -1,
  draggedItemId: -1,
  dragDropCategory: {
    entity: ['entityContainer'],
    association: ['entityClone'],
    attribute: ['entity', 'attributeContainer'],
    attributeContainer: ['entity'],
    EAD: ['entity'],
    factory: [],
    entityClone: ['association', 'EAD', 'entityContainer'],
    entityContainer: ['association', 'EAD'],
  },
  restrictedParentIds: [],
  disabledChildIds: [],
  idCount: 12,
  expandAll: false,
  compactMode: false,
};

export default initialState;
