const testInitialState = {
  version: '0.3.0',
  items: {
    0: {
      content: 'Initialize your project from EAD',
      subItemIds: [
        1,
        9,
      ],
      order: 'vertical',
      subdirection: 'row',
      isDropDisabled: true,
      isDragDisabled: true,
      expand: true,
    },
    1: {
      content: 'Elements',
      subItemIds: [
        2,
        3,
        4,
        5,
        6,
        7,
        8,
      ],
      order: 'vertical',
      subdirection: 'column',
      isDropDisabled: true,
      isDragDisabled: true,
      expand: true,
      factory: true,
      category: 'factory',
    },
    2: {
      content: 'has_many',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: true,
      factory: true,
      association: true,
      expand: true,
      category: 'association',
    },
    3: {
      content: 'has_one',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: true,
      factory: true,
      association: true,
      expand: true,
      category: 'association',
    },
    4: {
      content: ':through',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: true,
      factory: true,
      association: true,
      expand: true,
      category: 'association',
    },
    5: {
      content: 'entities & associations',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: true,
      factory: true,
      type: 'string',
      expand: true,
      entityAssociation: true,
      category: 'entityAssociation',
    },
    6: {
      content: 'attribute',
      subItemIds: [],
      attribute: true,
      order: 'vertical',
      subdirection: 'column',
      isDropDisabled: true,
      factory: true,
      type: 'string',
      expand: true,
      category: 'attribute',
    },
    7: {
      content: 'entity',
      subItemIds: [],
      order: 'vertical',
      subdirection: 'column',
      factory: true,
      entity: true,
      expand: true,
      isDropDisabled: true,
      category: 'entity',
      cloneable: true,
      cloneChildren: [],
    },
    8: {
      content: 'entity container',
      subItemIds: [],
      order: 'vertical',
      subdirection: 'column',
      factory: true,
      entityContainer: true,
      expand: true,
      isDropDisabled: true,
      category: 'entityContainer',
    },
    9: {
      content: 'EAD',
      subItemIds: [
        10,
        11,
      ],
      order: 'horizontal',
      subdirection: 'row',
      isDragDisabled: true,
      expand: true,
      category: 'EAD',
    },
    10: {
      content: 'entity container',
      subItemIds: [
        16,
        13,
        12,
      ],
      order: 'vertical',
      subdirection: 'column',
      entityContainer: true,
      expand: true,
      category: 'entityContainer',
      factory: false,
      isDropDisabled: false,
    },
    11: {
      content: 'entities & associations',
      subItemIds: [
        24,
        23,
        17,
      ],
      order: 'horizontal',
      subdirection: 'row',
      entityAssociation: true,
      expand: true,
      category: 'entityAssociation',
      factory: false,
      isDropDisabled: false,
    },
    12: {
      content: 'appointment',
      subItemIds: [
        15,
      ],
      order: 'vertical',
      subdirection: 'column',
      factory: false,
      entity: true,
      expand: true,
      isDropDisabled: false,
      category: 'entity',
      cloneable: true,
      cloneChildren: [
        19,
      ],
    },
    13: {
      content: 'physician',
      subItemIds: [
        14,
      ],
      order: 'vertical',
      subdirection: 'column',
      factory: false,
      entity: true,
      expand: true,
      isDropDisabled: false,
      category: 'entity',
      cloneable: true,
      cloneChildren: [
        17,
      ],
    },
    14: {
      content: 'name',
      subItemIds: [],
      attribute: true,
      order: 'vertical',
      subdirection: 'column',
      isDropDisabled: false,
      factory: false,
      type: 'string',
      expand: true,
      category: 'attribute',
    },
    15: {
      content: 'attribute',
      subItemIds: [],
      attribute: true,
      order: 'vertical',
      subdirection: 'column',
      isDropDisabled: false,
      factory: false,
      type: 'string',
      expand: true,
      category: 'attribute',
    },
    16: {
      content: 'patient',
      subItemIds: [],
      order: 'vertical',
      subdirection: 'column',
      factory: false,
      entity: true,
      expand: true,
      isDropDisabled: false,
      category: 'entity',
      cloneable: true,
      cloneChildren: [
        21,
        23,
        24,
      ],
    },
    17: {
      content: 'physician',
      subItemIds: [
        18,
      ],
      order: 'horizontal',
      subdirection: 'row',
      factory: false,
      expand: true,
      isDropDisabled: false,
      category: 'entityClone',
      entityClone: true,
      cloneParent: 13,
      parentId: 11,
      parentIndex: 0,
    },
    18: {
      content: 'has_many',
      subItemIds: [
        19,
      ],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: false,
      factory: false,
      association: true,
      expand: true,
      category: 'association',
    },
    19: {
      content: 'appointments',
      subItemIds: [
        22,
      ],
      order: 'horizontal',
      subdirection: 'row',
      factory: false,
      expand: true,
      isDropDisabled: false,
      category: 'entityClone',
      entityClone: true,
      cloneParent: 12,
      parentId: 18,
      parentIndex: 0,
    },
    21: {
      content: 'patients',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      factory: false,
      expand: true,
      isDropDisabled: false,
      category: 'entityClone',
      entityClone: true,
      cloneParent: 16,
      parentId: '22',
      parentIndex: 0,
    },
    22: {
      content: ':through',
      subItemIds: [
        21,
      ],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: false,
      factory: false,
      association: true,
      expand: true,
      category: 'association',
    },
    23: {
      content: 'patient',
      subItemIds: [
        25,
      ],
      order: 'horizontal',
      subdirection: 'row',
      factory: false,
      expand: true,
      isDropDisabled: false,
      category: 'entityClone',
      entityClone: true,
      cloneParent: 16,
      parentId: 11,
      parentIndex: 0,
    },
    24: {
      content: 'patient',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      factory: false,
      expand: true,
      isDropDisabled: false,
      category: 'entityClone',
      entityClone: true,
      cloneParent: 16,
      parentId: 11,
      parentIndex: 0,
    },
    25: {
      content: 'has_many',
      subItemIds: [],
      order: 'horizontal',
      subdirection: 'row',
      isDropDisabled: false,
      factory: false,
      association: true,
      expand: true,
      category: 'association',
    },
  },
  restrictedDropId: -1,
  draggedItemId: -1,
  dragDropCategory: {
    entity: [
      'entityContainer',
    ],
    association: [
      'entityClone',
    ],
    entityAssociation: [
      'EAD',
    ],
    attribute: [
      'entity',
      'attributeContainer',
    ],
    attributeContainer: [
      'entity',
    ],
    EAD: [
      'entity',
    ],
    factory: [],
    entityClone: [
      'association',
      'entityAssociation',
    ],
    entityContainer: [
      'EAD',
    ],
  },
  restrictedParentIds: [],
  disabledChildIds: [],
  idCount: 26,
  expandAll: false,
  compactMode: false,
  moreText: false,
};

export default testInitialState;
